### ISSUE TITLE
can't install from hex.pm

### ISSUE THREAD

**Issue by hxgdzyuyi** [arikai/icalendar#1]
:icalendar in hex.pm is  https://github.com/lpil/icalendar

**Comment by jrogov** [comment]
Library on Hex is a different one.
This library is under a heavy development.

**Comment by hxgdzyuyi** [comment]
But it's useful. I want to use it.

**Comment by jrogov** [comment]
@hxgdzyuyi I understand that, yet for now I don't have enough time to complete this library for wider use.
However, contributions are welcome!

Hope it can be of any use in it's current state and I will be able to complete this in the future.
